name: Style check

on:
  workflow_run:
    workflows: ["Running code"]
    types: [completed]
  push:
    branches:
      - main
      - set-up-assignment
      - try
  pull_request:
    branches:
      - main 
      - master
      - dev
      - submission
      - try
    paths:
      - 'src/*.py'
      - '*.py'

jobs:
  flake8_py3:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.18
          architecture: x64

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 --ignore=E402
